### ISSUE TITLE
Documentation updation

### ISSUE THREAD

**Issue by Sloth-Panda** [Saikat-98/World-Covid-Tracker#25]
![Screenshot (50)](https://user-images.githubusercontent.com/70213384/104657400-ea66bb00-56e6-11eb-9394-ae455221b00b.png)

there are spelling errors due to just copying of codes so will like to work on this issue let me know.
Complete Project name is written something else

**Comment by isaikatofficial** [comment]
Yes,Go ahead, also please update the pics and gifs, I will be adding dark theme as well by eod tomorrow!!

**Comment by Sloth-Panda** [comment]
@saikat which pics??  are you talking about those emojis?

**Comment by isaikatofficial** [comment]
The dark theme pics/ gifs.... of the app... I will be adding those by eod today.
