### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by musavveer** [Saikat-98/World-Covid-Tracker#8]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out:  https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me. @Saikat-98

**Comment by isaikatofficial** [comment]
Go ahead start working on it, I will assign it to you.

**Comment by samir-0711** [comment]
I would like to work on this.
